sudo: required

service: docker

before_install:
  - docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails rb:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails rb:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web bundle exec rspec